name: Production

on:
  push:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build
        run: |
          echo "${{ secrets.ENV }}" > .env
          npm run build
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws s3 sync ./build s3://about-hoseung --acl public-read --delete
          aws cloudfront create-invalidation --distribution-id E31H7NOZM0QJVH --paths "/*"
